language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t martin-luo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true martin-luo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ""
  app: "docker"
  environment: "Docker-env"
  bucket_name: ""
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
