# Base image
FROM node:14.15.1-alpine3.10

# Set up the working directory
WORKDIR '/app'

# Copy package.json and install dependencies
COPY package.json .
RUN npm install

# Copy other files
COPY . .

# Command to run the app
CMD ["npm", "run", "start"]

# Command to run the docker :
# docker run -it -p 3000:3000 -v /app/node_modules -v "$(pwd):/app" IMAGE_ID
